import type { Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import SyncUser from './components/SyncUser'
import Navbar from './components/NavBar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Job Fit',
  description: 'Generated by YM',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
  signUpForceRedirectUrl="/onboarding"
 >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>  
        <Navbar />
        <SyncUser />
          {children}
        </body>
      </html>
    </ClerkProvider>
     )
}